from enum import Enum

class ReportCategory(str, Enum):
    CONSULTANT_SUMMARY = "CONSULTANT_SUMMARY"
    REQUIREMENT_PIPELINE = "REQUIREMENT_PIPELINE"
    SUBMISSION_REPORT = "SUBMISSION_REPORT"
    INTERVIEW_REPORT = "INTERVIEW_REPORT"
    PLACEMENT_REPORT = "PLACEMENT_REPORT"
    RECRUITER_PERFORMANCE = "RECRUITER_PERFORMANCE"
    VENDOR_ANALYTICS = "VENDOR_ANALYTICS"
    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"
    AUDIT_HISTORY = "AUDIT_HISTORY"

class ExportFormat(str, Enum):
    CSV = "CSV"
    XLSX = "XLSX"
    PDF = "PDF"
    JSON = "JSON"

class ReportExecutionStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"