from enum import Enum

class NotificationType(str, Enum):
    FOLLOW_UP_DUE = "FOLLOW_UP_DUE"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_REMINDER = "INTERVIEW_REMINDER"
    INTERVIEW_FEEDBACK_PENDING = "INTERVIEW_FEEDBACK_PENDING"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    OFFER_EXPIRING = "OFFER_EXPIRING"
    PLACEMENT_CONFIRMED = "PLACEMENT_CONFIRMED"
    CONSULTANT_AVAILABLE = "CONSULTANT_AVAILABLE"
    REQUIREMENT_OPENED = "REQUIREMENT_OPENED"
    REQUIREMENT_STALE = "REQUIREMENT_STALE"
    SYSTEM_ALERT = "SYSTEM_ALERT"

class DeliveryChannel(str, Enum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    SMS = "SMS"
    SLACK = "SLACK"
    TEAMS = "TEAMS"
    WEBHOOK = "WEBHOOK"

class NotificationPriority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class NotificationStatus(str, Enum):
    UNREAD = "UNREAD"
    READ = "READ"
    DISMISSED = "DISMISSED"