from enum import Enum


class MarketingActivityType(str, Enum):
    PROFILE_MARKETING = "PROFILE_MARKETING"
    PROFILE_FOLLOW_UP = "PROFILE_FOLLOW_UP"
    REQUIREMENT_OUTREACH = "REQUIREMENT_OUTREACH"
    VENDOR_OUTREACH = "VENDOR_OUTREACH"
    CLIENT_OUTREACH = "CLIENT_OUTREACH"
    MARKETING_REFRESH = "MARKETING_REFRESH"


class MarketingChannel(str, Enum):
    EMAIL = "EMAIL"
    PHONE_CALL = "PHONE_CALL"
    LINKEDIN = "LINKEDIN"
    PORTAL = "PORTAL"
    SMS = "SMS"
    OTHER = "OTHER"


class MarketingOutcome(str, Enum):
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    RESPONDED = "RESPONDED"
    INTERESTED = "INTERESTED"
    NO_RESPONSE = "NO_RESPONSE"
    NOT_INTERESTED = "NOT_INTERESTED"
    REQUIREMENT_RECEIVED = "REQUIREMENT_RECEIVED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    FAILED = "FAILED"