from enum import Enum

class AutomationTriggerType(str, Enum):
    SUBMISSION_CREATED = "SUBMISSION_CREATED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    PLACEMENT_CREATED = "PLACEMENT_CREATED"
    REQUIREMENT_OPENED = "REQUIREMENT_OPENED"
    REQUIREMENT_STALE = "REQUIREMENT_STALE"
    TASK_OVERDUE = "TASK_OVERDUE"
    NOTIFICATION_UNREAD = "NOTIFICATION_UNREAD"

class AutomationActionType(str, Enum):
    CREATE_TASK = "CREATE_TASK"
    SEND_NOTIFICATION = "SEND_NOTIFICATION"
    ADD_TIMELINE_NOTE = "ADD_TIMELINE_NOTE"
    CREATE_BUSINESS_EVENT = "CREATE_BUSINESS_EVENT"
    CALL_WEBHOOK = "CALL_WEBHOOK"
    QUEUE_EMAIL = "QUEUE_EMAIL"

class ExecutionStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"