from enum import Enum

class BusinessEventType(str, Enum):
    CONSULTANT_CREATED = "CONSULTANT_CREATED"
    MARKETING_STATUS_CHANGED = "MARKETING_STATUS_CHANGED"
    REQUIREMENT_OPENED = "REQUIREMENT_OPENED"
    SUBMISSION_CREATED = "SUBMISSION_CREATED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    OFFER_ACCEPTED = "OFFER_ACCEPTED"
    PLACEMENT_CREATED = "PLACEMENT_CREATED"
    REQUIREMENT_CLOSED = "REQUIREMENT_CLOSED"