from enum import Enum

class AuditActionType(str, Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    STATUS_CHANGE = "STATUS_CHANGE"
    WORKFLOW_EXECUTION = "WORKFLOW_EXECUTION"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    EXPORT = "EXPORT"
    IMPORT = "IMPORT"
    PERMISSION_CHANGE = "PERMISSION_CHANGE"
    CONFIGURATION_CHANGE = "CONFIGURATION_CHANGE"