from enum import Enum

class TaskType(str, Enum):
    FOLLOW_UP_VENDOR = "FOLLOW_UP_VENDOR"
    FOLLOW_UP_CLIENT = "FOLLOW_UP_CLIENT"
    FOLLOW_UP_CONSULTANT = "FOLLOW_UP_CONSULTANT"
    SUBMIT_PROFILE = "SUBMIT_PROFILE"
    REQUEST_FEEDBACK = "REQUEST_FEEDBACK"
    INTERVIEW_PREPARATION = "INTERVIEW_PREPARATION"
    INTERVIEW_FOLLOW_UP = "INTERVIEW_FOLLOW_UP"
    OFFER_REVIEW = "OFFER_REVIEW"
    PLACEMENT_CONFIRMATION = "PLACEMENT_CONFIRMATION"
    RESUME_REFRESH = "RESUME_REFRESH"
    MARKETING_REFRESH = "MARKETING_REFRESH"
    GENERAL = "GENERAL"

class TaskStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    LIMIT_BREACHED = "LIMIT_BREACHED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"

class TaskPriority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"